### ISSUE TITLE
decoding 

### ISSUE THREAD

**Issue by nesquik011** [elerac/structured_light#1]
does it export .ply or any even point cloud ?

**Comment by elerac** [comment]
Hi @nesquik011,

Unfortunately, this repository does not support the feature to export any type of 3D data.

Decoding finds the corresponding points(2D to 2D) between the projector and the camera. To obtain the 3D data, a program to calibrate and calculate the 3D points is required separately.

**Comment by nesquik011** [comment]
so it only make decoding ? and are you planning to upgrade

**Comment by elerac** [comment]
Yes, decoding only.
There are no plans to upgrade at the moment.
