### ISSUE TITLE
Decoding stereo images?

### ISSUE THREAD

**Issue by metobom** [elerac/structured_light#4]
Is there a way to decode stereo images?

**Comment by elerac** [comment]
Hi @metobom !

Does "stereo images" mean images taken by **only** two (or more) camera pairs?

If so, I'm afraid I can't help you.
Structure-light systems mainly assume projector and camera pairs (a.k.a. projector-camera or pro-cam). So, if you want to decode images only from the camera, this repository may not be suitable for your purpose.

If not, and you mean projector-camera systems. Let me know more details of your purpose and system configuration.

**Comment by metobom** [comment]
I meant stereo but actually I am trying to measure parts of an object in x, y, and z, where the camera is the origin. For example, I want to know how far the leg of a scanned action figure and what is the size of leg in cm. Can achieve that with projector and camera setup?

**Comment by elerac** [comment]
@metobom 

> Can achieve that with projector and camera setup?

Yes, you will.

It looks that the projector-camera system is one of the good choices for your purpose. However, as you may know, these 3D measurements technique require complex processes (e.g., calibration, acquire correspondence, calculate 3D points). So, it is **hard to create the pro-cam system** from the ground up. 

Therefore, if you want to do just 3D measurement, I recommend using a commercial 3D scanner (such as [Intel RealSense](https://www.intelrealsense.com/lidar-camera-l515/), [Desktop 3D Scanner](https://www.einscan.com/desktop-3d-scanners/), or [iPhone with 3D scan app](https://www.scandy.co/apps/scandy-pro)).

Or, if you want to create an original scanner that is research-oriented and/or customizable, this repository will help you.

**Comment by metobom** [comment]
I like to create one myself. I don't know how can I triangulate points with a projector and camera. Do you have any sources to read?

**Comment by elerac** [comment]
Yes!

[Nayar's videos](https://www.youtube.com/channel/UCf0WB91t8Ky6AuYcQV0CcLw/featured) are good for a first step.
- [Linear Camera Model](https://youtu.be/qByYk6JggQU)
- [Camera Calibration](https://youtu.be/GUbWsXU1mac)
- [Intrinsic and Extrinsic Matrices](https://youtu.be/2XM2Rb2pfyQ)
- [Simple Stereo](https://youtu.be/hUVyDabn1Mg)
- [Structured Light Range Finding](https://youtu.be/3S3xLUXAgHw)
- [Phase Shifting Method](https://youtu.be/_Vo9Vcecwo0)
- [Structured Light Systems](https://youtu.be/OZf8ki5Givo)

[Gkioulekas's course](http://graphics.cs.cmu.edu/courses/15-463/2018_fall/) releases great slides for computational photography.
- [Camera models and calibration](http://graphics.cs.cmu.edu/courses/15-463/2018_fall/lectures/lecture13.pdf)
- [Two-view geometry](http://graphics.cs.cmu.edu/courses/15-463/2018_fall/lectures/lecture15.pdf)
- [Stereo and structured light](http://graphics.cs.cmu.edu/courses/15-463/2018_fall/lectures/lecture20.pdf)

This SIGGRAPH course finds out practical ways.
- [Build Your Own 3D Scanner: Optical Triangulation for Beginners](http://mesh.brown.edu/byo3d/index.html)
